USE college;
CREATE TABLE college (
  id INT(3) UNSINGED NOT NULL DEFAULT NULL auto_increment,
  title VARCHAR(255) NOT NULL UNIQUE DEFAULT NULL,
  credits TINYINT(2) UNSINGED NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
) AUTO_INCREMENT = 1;
